#!/usr/bin/env python3

import sys
from alembic.config import Config, CommandLine
from webapp.database import DB_URL

cmdline = CommandLine()
args = sys.argv[1:] or [""]
options = cmdline.parser.parse_args(args)

config = Config()
config.set_main_option("script_location", "migrations")
config.set_main_option("sqlalchemy.url", DB_URL)

cmdline.run_cmd(config, options)
