#! /usr/bin/env bash

set -euo pipefail
export FLASK_APP=webapp.app

activate() {
    # Create or activate virtualenv
    if [ ! -d ./.venv ]; then
        python3 -m venv .venv
    fi
    . ./.venv/bin/activate
}

{
    activate

    RUN_COMMAND="talisker.gunicorn webapp.app:app --bind $1 --worker-class sync --workers 3 --name talisker-$(hostname)"

    if [ "${FLASK_DEBUG}" = true ] || [ "${FLASK_DEBUG}" = 1 ]; then
        RUN_COMMAND="${RUN_COMMAND} --reload --log-level debug --timeout 9999"
    fi

    # Run migrations
    alembic upgrade head

    # Start the website
    ${RUN_COMMAND}

}
