Products:
  - name: "Ubuntu Frame"
    slug: "ubuntu-frame"
  - name: "Support"
    slug: "support"
  - name: "ESM"
    slug: "esm"
  - name: "MicroCloud"
    slug: "microcloud"
  - name: "Cube"
    slug: "cube"
  - name: "Managed Apps"
    slug: "managed-apps"
  - name: "Ubuntu Core / Snapd"
    slug: "ubuntu-core-snapd"
  - name: "Ubuntu Pro"
    slug: "ubuntu-pro"
  - name: "Snapcraft"
    slug: "snapcraft"
  - name: "Security"
    slug: "security"
  - name: "Edge"
    slug: "edge"
  - name: "Launchpad"
    slug: "launchpad"
  - name: "Industrial"
    slug: "industrial"
  - name: "Security - Tech"
    slug: "security-tech"
  - name: "Security Notices"
    slug: "security-notices"
  - name: "Smart Displays (Mir)"
    slug: "smart-displays-mir"
  - name: "Multipass"
    slug: "multipass"
  - name: "Data - Big Data"
    slug: "data-big-data"
  - name: "Charm Collection"
    slug: "charm-collection"
  - name: "Smart Home"
    slug: "smart-home"
  - name: "Embedding"
    slug: "embedding"
  - name: "Charmed Openstack"
    slug: "charmed-openstack"
  - name: "Observability"
    slug: "observability"
  - name: "FIPS"
    slug: "fips"
  - name: "Canonical Openstack"
    slug: "canonical-openstack"
  - name: "Canonical K8s"
    slug: "canonical-k8s"
  - name: "Identity"
    slug: "identity"
  - name: "Finance"
    slug: "finance"
  - name: "Real-Time Kernel"
    slug: "real-time-kernel"
  - name: "Blender"
    slug: "blender"
  - name: "Robotics"
    slug: "robotics"
  - name: "Kernel Factory"
    slug: "kernel-factory"
  - name: "WSL"
    slug: "wsl"
  - name: "Managed Infra"
    slug: "managed-infra"
  - name: "Microstack"
    slug: "microstack"
  - name: "Appliance Portfolio"
    slug: "appliance-portfolio"
  - name: "Networking"
    slug: "networking"
  - name: "Juju"
    slug: "juju"
  - name: "Snap Store"
    slug: "snap-store"
  - name: "Public Cloud"
    slug: "public-cloud"
  - name: "Charmed K8s"
    slug: "charmed-k8s"
  - name: "Store"
    slug: "store"
  - name: "Microcloud/LXD"
    slug: "microcloud-lxd"
  - name: "Rocks"
    slug: "rocks"
  - name: "AI/ML"
    slug: "ai-ml"
  - name: "Pro for devices"
    slug: "pro-for-devices"
  - name: "Charm Hub"
    slug: "charm-hub"
  - name: "Kernel"
    slug: "kernel"
  - name: "Anbox"
    slug: "anbox"
  - name: "Juggle"
    slug: "juggle"
  - name: "Microk8s"
    slug: "microk8s"
  - name: "Desktop"
    slug: "desktop"
  - name: "Embedded"
    slug: "embedded"
  - name: "HPC"
    slug: "hpc"
  - name: "Data - SQL"
    slug: "data-sql"
  - name: "Livepatch"
    slug: "livepatch"
  - name: "GSI"
    slug: "gsi"
  - name: "Landscape"
    slug: "landscape"
  - name: "Telco"
    slug: "telco"
  - name: "Jaas"
    slug: "jaas"
  - name: "Automotive"
    slug: "automotive"
  - name: "Robotics Developers"
    slug: "robotics-developers"
  - name: "MAAS"
    slug: "maas"
  - name: "EdgeX"
    slug: "edgex"
  - name: "Kubeflow / AI"
    slug: "kubeflow-ai"
  - name: "Data Platform"
    slug: "data-platform"
  - name: "AKS/EKS/GKE"
    slug: "aks-eks-gke"
  - name: "Ubuntu Core / Snapd Ux"
    slug: "ubuntu-core-snapd-ux"
  - name: "Ubuntu Core / Snapd Docs"
    slug: "ubuntu-core-snapd-docs"
  - name: "Hardening"
    slug: "hardening"
  - name: "Kernos"
    slug: "kernos"
  - name: "Ceph"
    slug: "ceph"
  - name: "Server"
    slug: "server"
  - name: "UA-A (Adv/Std/Ess)"
    slug: "ua-a-adv-std-ess"
  - name: "Data - NoSQL"
    slug: "data-nosql"
  - name: "IOT Management"
    slug: "iot-management"
  - name: "HW Certification"
    slug: "hw-certification"
  - name: "Raspberrypi"
    slug: "raspberrypi"
  - name: "Other"
    slug: "other"
  - name: "LXD"
    slug: "lxd"
