version: "3"

dotenv: [".env", ".env.local"]

tasks:
  default:
    desc: "Start the project"
    cmds:
      - docker compose up -d

  stop:
    desc: "Stop the project"
    cmds:
      - docker compose down

  cleanup:
    desc: "Stop containers and remove volumes"
    cmds:
      - docker compose down -v

  rebuild:
    desc: "Rebuild the project. Only run this if you have made changes to the Docker related files (Dockerfile, docker-compose.yaml)."
    cmds:
      - docker compose up -d --build

  format-python:
    desc: "Format python code"
    cmds:
      - docker exec assetsubuntucom-app-1 yarn format-python

  lint:
    desc: "Run code linters"
    cmds:
      - docker exec assetsubuntucom-app-1 yarn lint