"""add tags

Revision ID: 6652ef3aa77f
Revises: a2f0126f69b8
Create Date: 2021-11-04 18:42:16.308477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6652ef3aa77f"
down_revision = "a2f0126f69b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "asset_tag_association",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_name"],
            ["tag.name"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "tag_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset_tag_association")
    op.drop_table("tag")
    # ### end Alembic commands ###
