"""added salesforce_campaign and asset association

Revision ID: 7059dcc76605
Revises: 14e1e1dfca79
Create Date: 2025-07-24 11:09:29.779605

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7059dcc76605"
down_revision = "14e1e1dfca79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesforce_campaign",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset_campaign_association",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["salesforce_campaign.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "campaign_id"),
    )
    op.drop_column("asset", "salesforce_campaign_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "asset",
        sa.Column(
            "salesforce_campaign_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("asset_campaign_association")
    op.drop_table("salesforce_campaign")
    # ### end Alembic commands ###
