"""added portfolio and vertical

Revision ID: bebbc242e9b1
Revises: 14e1e1dfca79
Create Date: 2025-07-15 10:38:51.189151

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bebbc242e9b1"
down_revision = "14e1e1dfca79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset", sa.Column("vertical", sa.String(), nullable=True))
    op.add_column("asset", sa.Column("portfolio", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset", "portfolio")
    op.drop_column("asset", "vertical")
    # ### end Alembic commands ###
