"""add categories to assets

Revision ID: def1b50e89fa
Revises: 7059dcc76605
Create Date: 2025-09-23 13:54:08.000678

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "def1b50e89fa"
down_revision = "7059dcc76605"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "asset_category_association",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_name"],
            ["category.name"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "category_name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset_category_association")
    op.drop_table("category")
    # ### end Alembic commands ###
